### ISSUE TITLE
Feature Request Review

### ISSUE THREAD

**Issue by mp1pro** [codesofter/daily#9]
Adding the ability to trigger the search function by pressing enter button will indeed make the app faster to navigate. This will also improve the users experience and interface. The technical design you have layed out for the enter key is correct. The code is correct.

Using the ladda buttons is a great idea. The user would definitely want to know what is the status of their request. Using a third party component is faster for development however, I think you have enough technical detail to create your own. You would just need to get a response from `Spotify.search(term)` then you could use setState to change `searchButtonLoading`. Then create your own ButtonLoading Component that use these states to toggle loading gifs on or off.

**Comment by codesofter** [comment]
Well.. good thing that's exactly what I did. I only use third party css for the loading. Thanks Marvin.
